# Generated by Django 2.2.5 on 2019-09-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190912_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
